//! The Hilbert recursion.  Top-level entry points and the
//! `BigRecPoincare`/`SplitPoincare`/`TotalSplitPoincare` family.
//!
//! Port of CoCoA-EP's `BigRecPoincare`, `SplitPoincare`, `TotalSplitPoincare`
//! and the `TLPoincareNumeratorCPP` entry point from `TmpPoincareCPP.C`.
//!
//! See `chat/plan-v2/R2_hilbert.md` §5 H4–H5.

use crate::homomorphism::Homomorphism;
use crate::ring::*;
use crate::rings::poly::*;
use crate::rings::poly::dense_poly::DensePolyRing;
use crate::integer::BigIntRing;

use super::term_list::{
    EMonom, TermList, big_pivot_of, move_not_coprime, split_indets,
};
use super::reduce::reduce_and_divide_by_simple_power;
use super::leaves::{ZT, sp_poincare, len_one_poincare, one_term_and_sp_poincare};
use super::uni_helpers::mul_by_1_minus_xk;

// ----------------------------------------------------------------------------
// Total split: every mixed term is coprime with every other → factorise.
// ----------------------------------------------------------------------------

/// CoCoA `TotalSplitPoincare`: invoked when `BigPivotOf` returns no
/// most-frequent indet, i.e. every var appears at most once in the mixed
/// list.  Each mixed term is then independent and the numerator factorises
/// across them; SP contributes its own `(1 - t^{sp[i]})` factors.
fn total_split_poincare(zt: &ZT, mut tl: TermList) -> El<ZT> {
    let n_vars = tl.n_vars();
    let mixed = std::mem::take(&mut tl.mixed);
    // Swap SP out (EMonom isn't Default; use an empty placeholder).
    let mut sp = std::mem::replace(&mut tl.sp, EMonom::one(n_vars));
    let _ = tl;

    let mut res: Option<El<ZT>> = None;
    let mut coprime_degs: Vec<usize> = Vec::new();

    for term in mixed.iter() {
        let mut local_sp = EMonom::one(n_vars);
        super::term_list::move_not_coprime_sp(&mut sp, &mut local_sp, term);
        if local_sp.occ_count() != 0 {
            let factor = one_term_and_sp_poincare(zt, term, &local_sp);
            res = Some(match res {
                Some(prev) => zt.mul_ref(&prev, &factor),
                None => factor,
            });
        } else {
            coprime_degs.push(term.degree() as usize);
        }
    }

    let leftover = sp_poincare(zt, &sp);
    let mut res = match res {
        Some(prev) => zt.mul_ref(&prev, &leftover),
        None => leftover,
    };
    for d in coprime_degs {
        mul_by_1_minus_xk(zt, &mut res, d);
    }
    res
}

// ----------------------------------------------------------------------------
// SplitPoincare: variable-disjoint connected components.
// ----------------------------------------------------------------------------

/// CoCoA `SplitPoincare`: invoked when `SplitIndets` reveals ≥ 2 connected
/// components in the variable-incidence hypergraph.  Each component is
/// recursed on separately; SP and "isolated" mixed terms (those that fell
/// into a singleton group) get multiplied in at the end as plain
/// `(1 - t^k)` factors.
fn split_poincare(zt: &ZT, mut tl: TermList, splitter: Vec<EMonom>) -> El<ZT> {
    let n_vars = tl.n_vars();
    let mut isolated_degs: Vec<usize> = Vec::new();
    let mut res: Option<El<ZT>> = None;

    // For each splitter group, peel off a sub-TermList of `tl` consisting
    // of mixed/SP entries that intersect the group's support.  Recurse.
    for group in splitter.into_iter() {
        let mut sub = TermList::empty(n_vars);
        move_not_coprime(&mut tl, &mut sub, &group);
        // CoCoA's optimisation: if the sub has exactly one mixed term and
        // empty SP, the recursion would just yield `(1 - t^{deg m})`, so
        // we queue the degree and skip the call.
        if sub.mixed.len() == 1 && sub.sp.occ_count() == 0 {
            isolated_degs.push(sub.mixed[0].degree() as usize);
        } else {
            let sub_h = big_rec_poincare(zt, sub);
            res = Some(match res {
                Some(prev) => zt.mul_ref(&prev, &sub_h),
                None => sub_h,
            });
        }
    }

    // Leftover: SP entries never absorbed by any group, plus any mixed
    // terms that survived (none should, since SplitIndets covered every
    // mixed term, but be defensive).
    debug_assert!(tl.mixed.is_empty(), "SplitPoincare: mixed not fully consumed");
    let leftover = sp_poincare(zt, &tl.sp);
    let mut res = match res {
        Some(prev) => zt.mul_ref(&prev, &leftover),
        None => leftover,
    };
    for d in isolated_degs {
        mul_by_1_minus_xk(zt, &mut res, d);
    }
    res
}

// ----------------------------------------------------------------------------
// BigRecPoincare: the main recursion driver.
// ----------------------------------------------------------------------------

/// CoCoA `BigRecPoincare`.  Recursively computes the Hilbert numerator of
/// `R / I` where `I` is the monomial ideal generated by `tl.sp ∪ tl.mixed`.
pub fn big_rec_poincare(zt: &ZT, mut tl: TermList) -> El<ZT> {
    if tl.mixed.is_empty() {
        return sp_poincare(zt, &tl.sp);
    }
    if tl.mixed.len() == 1 {
        return len_one_poincare(zt, &tl);
    }
    let pivot = match big_pivot_of(&tl) {
        None => {
            // No var occurs more than once → total split.
            return total_split_poincare(zt, tl);
        }
        Some((idx, deg)) => (idx, deg),
    };
    let (pi, pe) = pivot;

    // Try a connected-components split iff the recursion is in the
    // "interesting" regime (CoCoA: few mixed terms, many vars).
    if tl.mixed.len() < tl.n_vars() && tl.mixed.len() > 4 {
        if let Some(splitter) = split_indets(&tl) {
            return split_poincare(zt, tl, splitter);
        }
    }

    // Standard pivot recursion: H = H(I + x_pi^pe) + t^pe * H(I : x_pi^pe).
    let div = reduce_and_divide_by_simple_power(&mut tl, pi, pe);
    let mut h_kept = big_rec_poincare(zt, tl);
    let h_div = big_rec_poincare(zt, div);
    // h_kept += t^pe * h_div.
    let one_b = zt.base_ring().one();
    let h_div_terms: Vec<_> = zt
        .terms(&h_div)
        .map(|(c, d)| (zt.base_ring().mul_ref(&one_b, c), d + pe as usize))
        .collect();
    zt.get_ring().add_assign_from_terms(&mut h_kept, h_div_terms);
    h_kept
}

// ----------------------------------------------------------------------------
// Public entry point.
// ----------------------------------------------------------------------------

/// Compute the Hilbert numerator of `R / I` where:
///
/// * `R = k[x_1, ..., x_{n_vars}]` is standard-graded (one variable per
///   degree).
/// * `I` is the monomial ideal generated by `gens` (a list of leading
///   monomials).  Each `EMonom` in `gens` must have arity `n_vars`.
///
/// The returned polynomial `N(t) ∈ Z[t]` satisfies
/// `H_{R/I}(t) = N(t) / (1 - t)^{n_vars}`.
pub fn hilbert_numerator<I>(n_vars: usize, gens: I) -> El<ZT>
where
    I: IntoIterator<Item = EMonom>,
{
    let zt: ZT = DensePolyRing::new(BigIntRing::RING, "t");
    let tl = TermList::from_generators(n_vars, gens);
    big_rec_poincare(&zt, tl)
}

/// Variant that lets the caller supply a pre-built `Z[t]` ring (useful for
/// reusing a single `DensePolyRing` across many calls).
pub fn hilbert_numerator_in(zt: &ZT, n_vars: usize, gens: impl IntoIterator<Item = EMonom>) -> El<ZT> {
    let tl = TermList::from_generators(n_vars, gens);
    big_rec_poincare(zt, tl)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn em(n: usize, sp: &[(usize, u32)]) -> EMonom {
        EMonom::from_sparse(n, sp)
    }

    fn coeffs(z: &ZT, p: &El<ZT>) -> Vec<i64> {
        let d = z.degree(p).unwrap_or(0);
        let mut out = Vec::with_capacity(d + 1);
        for i in 0..=d {
            let c = z.coefficient_at(p, i);
            let s = format!("{}", z.base_ring().format(&c));
            out.push(s.parse::<i64>().expect("coeff out of i64"));
        }
        out
    }

    #[test]
    fn empty_ideal_gives_one() {
        // R / (0) has H = 1/(1-t)^n, so numerator = 1.
        let n = 3;
        let p = hilbert_numerator(n, std::iter::empty());
        let z: ZT = DensePolyRing::new(BigIntRing::RING, "t");
        // We have to rebuild a ZT to call coeffs; equivalent ring instances
        // since RingStore::eq is structural here.
        assert_eq!(coeffs(&z, &p), vec![1]);
    }

    #[test]
    fn maximal_ideal_in_one_var() {
        // R = k[x], I = (x).  H_{R/I}(t) = 1, so numerator * (1-t) = 1
        // ⇒ numerator = (1-t).  Wait — H = numerator / (1-t)^n with n=1.
        // R/I = k, so H = 1.  Then 1 = N / (1-t) ⇒ N = (1-t).
        let n = 1;
        let p = hilbert_numerator(n, vec![em(n, &[(0, 1)])]);
        let z: ZT = DensePolyRing::new(BigIntRing::RING, "t");
        assert_eq!(coeffs(&z, &p), vec![1, -1]);
    }

    #[test]
    fn regular_sequence_x_squared() {
        // R = k[x_0,x_1,x_2], I = (x_0^2, x_1^2, x_2^2).  This is a
        // complete intersection / regular sequence; the numerator is
        // (1 - t^2)^3 = 1 - 3 t^2 + 3 t^4 - t^6.
        let n = 3;
        let p = hilbert_numerator(n, vec![
            em(n, &[(0, 2)]), em(n, &[(1, 2)]), em(n, &[(2, 2)]),
        ]);
        let z: ZT = DensePolyRing::new(BigIntRing::RING, "t");
        assert_eq!(coeffs(&z, &p), vec![1, 0, -3, 0, 3, 0, -1]);
    }

    #[test]
    fn small_mixed_example() {
        // R = k[x,y], I = (x^2, x y, y^3).  The Hilbert function of R/I
        // is (1, 2, 1, 1, 1, 1, ...) — so H(t) = 1 + 2t + t^2 + t^3 / (1-t)
        // wait that's not finitely generated.  Let me just compute:
        //
        // R/I has basis {1, x, y, y^2}: dimension as k-vector space = 4.
        // R/I is artinian, so H_{R/I}(t) is a polynomial.  Computing from
        // the basis: deg 0 ⇒ {1} (1), deg 1 ⇒ {x, y} (2), deg 2 ⇒ {y^2} (1)
        // (since x^2 = xy = 0; xy is in I directly), deg 3+ ⇒ 0
        // (y^3 ∈ I).  So H(t) = 1 + 2t + t^2.
        //
        // Then numerator = H(t) * (1-t)^2 = (1 + 2t + t^2)(1 - 2t + t^2)
        //                = 1 + 2t + t^2 - 2t - 4t^2 - 2t^3 + t^2 + 2t^3 + t^4
        //                = 1 + 0t + (1 - 4 + 1) t^2 + 0 t^3 + t^4
        //                = 1 - 2t^2 + t^4.
        let n = 2;
        let p = hilbert_numerator(n, vec![
            em(n, &[(0, 2)]),
            em(n, &[(0, 1), (1, 1)]),
            em(n, &[(1, 3)]),
        ]);
        let z: ZT = DensePolyRing::new(BigIntRing::RING, "t");
        // The Hilbert numerator may differ from the canonical form by a
        // common (1-t)^k factor depending on whether the numerator is
        // reduced; CoCoA's `TLPoincareNumeratorCPP` returns the unreduced
        // (full) numerator.  Let's check unreduced first.  Actually with
        // n=2 vars and ideal generators, the unreduced numerator should be
        // exactly what we computed: 1 - 2t^2 + t^4 (degree 4).
        assert_eq!(coeffs(&z, &p), vec![1, 0, -2, 0, 1]);
    }

    #[test]
    fn variable_disjoint_factorisation() {
        // R = k[a,b,c,d], I = (a b, c d).  The two pieces are independent,
        // so numerator should factor: (1 - t^2)(1 - t^2) = 1 - 2t^2 + t^4.
        let n = 4;
        let p = hilbert_numerator(n, vec![
            em(n, &[(0, 1), (1, 1)]),
            em(n, &[(2, 1), (3, 1)]),
        ]);
        let z: ZT = DensePolyRing::new(BigIntRing::RING, "t");
        assert_eq!(coeffs(&z, &p), vec![1, 0, -2, 0, 1]);
    }

    #[test]
    fn bigger_regular_sequence() {
        // (x_0^3, x_1^3, x_2^3, x_3^3).  Numerator = (1-t^3)^4.
        // (1-t^3)^2 = 1 - 2t^3 + t^6.
        // (1-t^3)^4 = (1 - 2t^3 + t^6)^2 = 1 - 4t^3 + 6t^6 - 4t^9 + t^12.
        let n = 4;
        let p = hilbert_numerator(n, vec![
            em(n, &[(0, 3)]), em(n, &[(1, 3)]),
            em(n, &[(2, 3)]), em(n, &[(3, 3)]),
        ]);
        let z: ZT = DensePolyRing::new(BigIntRing::RING, "t");
        let mut want = vec![0i64; 13];
        want[0] = 1; want[3] = -4; want[6] = 6; want[9] = -4; want[12] = 1;
        assert_eq!(coeffs(&z, &p), want);
    }

    #[test]
    fn mixed_pivot_recursion_path() {
        // Force the standard pivot path with a small but non-trivial example.
        // I = (x_0 x_1, x_0 x_2, x_1 x_2) in k[x_0, x_1, x_2].
        // R/I has basis {1, x_0, x_1, x_2, x_0^2, x_1^2, x_2^2, x_0^3, ...}
        // i.e. monomials in only ONE variable.  Hilbert function:
        //   deg 0: 1; deg d ≥ 1: 3 (one per var).
        // H(t) = 1 + 3t + 3t^2 + ... = 1 + 3t/(1-t) = (1 + 2t)/(1-t).
        // Numerator (with denominator (1-t)^3) = (1 + 2t)/(1-t) * (1-t)^3
        //         = (1 + 2t)(1-t)^2 = (1 + 2t)(1 - 2t + t^2)
        //         = 1 - 2t + t^2 + 2t - 4t^2 + 2t^3 = 1 - 3t^2 + 2t^3.
        let n = 3;
        let p = hilbert_numerator(n, vec![
            em(n, &[(0, 1), (1, 1)]),
            em(n, &[(0, 1), (2, 1)]),
            em(n, &[(1, 1), (2, 1)]),
        ]);
        let z: ZT = DensePolyRing::new(BigIntRing::RING, "t");
        assert_eq!(coeffs(&z, &p), vec![1, 0, -3, 2]);
    }

    #[test]
    fn oracle_k4_edge_ideal() {
        // Edge ideal of K_4: I = (x_i x_j : 0 ≤ i < j ≤ 3) in k[x_0,..,x_3].
        // R/I basis = {monomials in ≤ 1 variable} = {1} ∪ {x_i^d : i, d ≥ 1}.
        // ⇒ H_{R/I}(d) = 1 if d=0, 4 if d ≥ 1.
        // ⇒ H(t) = (1 + 3t)/(1 - t).
        // ⇒ N(t) = (1 + 3t)(1-t)^3 = 1 - 6t^2 + 8t^3 - 3t^4.
        let n = 4;
        let mut gens = Vec::new();
        for i in 0..4 {
            for j in (i + 1)..4 {
                gens.push(em(n, &[(i, 1), (j, 1)]));
            }
        }
        let p = hilbert_numerator(n, gens);
        let z: ZT = DensePolyRing::new(BigIntRing::RING, "t");
        assert_eq!(coeffs(&z, &p), vec![1, 0, -6, 8, -3]);
    }

    #[test]
    fn oracle_path_graph_p4_edge_ideal() {
        // Edge ideal of P_4 (path 0-1-2-3): I = (x_0 x_1, x_1 x_2, x_2 x_3).
        // R/I has basis = "independent sets of P_4" weighted by monomials.
        // Independent sets of P_4 (size, count): {} (1), {0},{1},{2},{3} (4),
        //   {0,2},{0,3},{1,3} (3), {0,2,...}: of size ≥ 3 we have {0,2,3}? No,
        //   2-3 is edge. {0,2}: ok. {0,3}: ok. {1,3}: ok. Size-3: need 3
        //   pairwise-non-adjacent, only {0,2}∪? — 3 is adj to 2.  None.
        // So Hilbert function counts monomials whose support is independent.
        // For each independent set S, # monomials of support = S, deg d is
        //   C(d-1, |S|-1) for d ≥ |S|.  Generating function:
        //   ∑_{S indep} t^{|S|} / (1-t)^{|S|}.
        // = 1 + 4 · t/(1-t) + 3 · t^2/(1-t)^2.
        // Multiply by (1-t)^4:
        //   = (1-t)^4 + 4 t (1-t)^3 + 3 t^2 (1-t)^2.
        // (1-t)^4 = 1 - 4t + 6t^2 - 4t^3 + t^4.
        // 4t(1-t)^3 = 4t(1 - 3t + 3t^2 - t^3) = 4t - 12t^2 + 12t^3 - 4t^4.
        // 3t^2(1-t)^2 = 3t^2(1 - 2t + t^2) = 3t^2 - 6t^3 + 3t^4.
        // Sum:
        //   const: 1
        //   t:    -4 + 4 = 0
        //   t^2:   6 - 12 + 3 = -3
        //   t^3:  -4 + 12 - 6 = 2
        //   t^4:   1 - 4 + 3 = 0
        // ⇒ N(t) = 1 - 3t^2 + 2t^3.
        let n = 4;
        let p = hilbert_numerator(n, vec![
            em(n, &[(0, 1), (1, 1)]),
            em(n, &[(1, 1), (2, 1)]),
            em(n, &[(2, 1), (3, 1)]),
        ]);
        let z: ZT = DensePolyRing::new(BigIntRing::RING, "t");
        assert_eq!(coeffs(&z, &p), vec![1, 0, -3, 2]);
    }
}
